### PR TITLE
Set keepalive to On by default

### PR DESCRIPTION
**Pull request by dustints**

### CODE REVIEW

**Comment by ehelms** [comment]
Why do we need this fork and commit?

**Comment by dustints** [comment]
@ehelms I'm hoping to fix http://projects.theforeman.org/issues/10440.
We would like to set KeepAlive to On for Katello and smart-proxy but both puppet-foreman and puppet-pulp both `include apache`. @mmoll also pointed out that puppet-puppet and puppet-foreman both `include apache`.
@mmoll pointed out that he was already working on http://projects.theforeman.org/issues/10440
and already has a patch that is accepted for 2.0.0 of the puppetlabs-apache module. 

for the interim, solution @mmoll came up with is to simply fork and patch.

Another way might be to use https://docs.puppetlabs.com/hiera/1/puppet.html#automatic-parameter-lookup. will kafo work with this?

**Comment by mmoll** [comment]
http://projects.theforeman.org/issues/8489 is probably meant.

**Comment by dustints** [comment]
yup

**Comment by ehelms** [comment]
Is this going to be a 1-off solution for Katello only where we are carrying and pointing to this fork? Is KeepAlive a global Apache setting or a per vhost setting that we could take advantage of? I assume there are no issues with KeepAlive for Foreman, Katello, Pulp, or Clients?

**Comment by dustints** [comment]
@ehelms if we go with this solution, i think we will have to maintain this until we make it to puppetlabs-apache-2.0.0.

Not sure if KeepAlive will be an issue, is this something the foreman-users/foreman-dev community can give feed back on?

**Comment by dustints** [comment]
@ehelms re on global?
it's global to each apache installation.
but if we apply this patch and pull it into `katello-installer` it would prob affect Foreman/Katello/Pulp ecosystem.

**Comment by mmoll** [comment]
As already mentioned in IRC, it's only a performance optimization and there's no real pressure from the Foreman users to "fix" that. Personally, like lzap, I changed this on a server behind a slow connection and had good results, leading me to open that PR to puppetlabs-apache.

The reason why the change was only merged for puppetlabs-apache 2.0 is, that it changes default behaviour. I'm not happy about this, but for the time being this fact and Puppet behaviour regarding ```include``` and ```class``` with parameters leaving only a fork as working option, AFAICT.

IMHO, it's only about a decision of the Katello project, if it's worth to close the BZ mentioned yesterday in IRC by using this fork in katello-installer until puppetlabs-apache 2.0 is released and usable in *-installer or not.

**Comment by dustints** [comment]
@mmoll, @ehelms closing because it's fine to wait for 2.0.

**Pull request closed without merging**
